
import { ProcessStep, SimulationConfig } from './types';

export const DEFAULT_STEPS: ProcessStep[] = [
  {
    id: 'node-start-1',
    type: 'start',
    name: 'Online Orders',
    randomnessMode: 'fixed',
    arrivalModel: 'simple',
    arrivalInputMode: 'rate',
    arrivalUnit: 'h',
    capacity: 0,
    processingTime: 0,
    variance: 0,
    arrivalRate: 12,
    minArrivalRate: 8,
    maxArrivalRate: 20,
    arrivalBatchSize: 1,
    arrivalBatchIntervalMs: 0,
    demandModifiers: [],
    arrivalSchedule: [],
    arrivalEvents: [],
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#10b981',
    connections: [{ targetId: 'step-1', probability: 1.0 }],
    x: 100,
    y: 250
  },
  {
    id: 'step-1',
    type: 'process',
    name: 'Order Taking',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 2,
    processingTime: 2000,
    processingTimeUnit: 'ms',
    variance: 0,
    minProcessingTime: 1500,
    maxProcessingTime: 3000,
    rangeTimeUnit: 'ms',
    failureProbability: 0,
    cancellationProbability: 0.05, // 5% chance to drop out per second in queue
    color: '#3b82f6',
    connections: [{ targetId: 'step-2', probability: 1.0 }],
    x: 400,
    y: 250
  },
  {
    id: 'step-2',
    type: 'process',
    name: 'Preparation',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 3,
    processingTime: 4000,
    processingTimeUnit: 'ms',
    variance: 0,
    minProcessingTime: 3000,
    maxProcessingTime: 6000,
    rangeTimeUnit: 'ms',
    failureProbability: 0.1, // 10% chance to burn/fail
    cancellationProbability: 0,
    color: '#f59e0b',
    connections: [{ targetId: 'step-3', probability: 1.0 }],
    x: 800,
    y: 250
  },
  {
    id: 'step-3',
    type: 'process',
    name: 'Quality Check',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 1,
    processingTime: 1500,
    processingTimeUnit: 'ms',
    variance: 0,
    minProcessingTime: 1000,
    maxProcessingTime: 2000,
    rangeTimeUnit: 'ms',
    failureProbability: 0.05,
    cancellationProbability: 0,
    color: '#8b5cf6',
    connections: [
      { targetId: 'step-4', probability: 0.9 },
      { targetId: 'step-2', probability: 0.1 },
    ],
    x: 800,
    y: 600
  },
  {
    id: 'step-4',
    type: 'process',
    name: 'Packaging',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 2,
    processingTime: 1000,
    processingTimeUnit: 'ms',
    variance: 0,
    minProcessingTime: 800,
    maxProcessingTime: 1500,
    rangeTimeUnit: 'ms',
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#ec4899',
    connections: [{ targetId: 'node-end-1', probability: 1.0 }],
    x: 1200,
    y: 250
  },
  {
    id: 'node-end-1',
    type: 'end',
    name: 'Shipment',
    randomnessMode: 'fixed',
    capacity: 0,
    processingTime: 0,
    variance: 0,
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#ef4444',
    connections: [],
    x: 1500,
    y: 250
  }
];

export const ROUTING_DEMO_STEPS: ProcessStep[] = [
  {
    id: 'routing-start',
    type: 'start',
    name: 'Customer Demand Mix',
    randomnessMode: 'fixed',
    arrivalModel: 'simple',
    arrivalInputMode: 'rate',
    arrivalUnit: 'h',
    capacity: 0,
    processingTime: 0,
    variance: 0,
    arrivalRate: 36,
    minArrivalRate: 24,
    maxArrivalRate: 48,
    arrivalBatchSize: 1,
    arrivalBatchIntervalMs: 0,
    demandModifiers: [],
    arrivalSchedule: [],
    arrivalEvents: [],
    itemProfiles: [
      {
        id: 'standard',
        name: 'Standard',
        probability: 0.7,
        processingTimeMultiplier: 1,
        failureMultiplier: 1,
        cancellationMultiplier: 1,
        priority: 1,
        color: '#38bdf8',
      },
      {
        id: 'vip',
        name: 'VIP',
        probability: 0.3,
        processingTimeMultiplier: 0.85,
        failureMultiplier: 0.7,
        cancellationMultiplier: 0.6,
        priority: 5,
        color: '#f472b6',
      },
    ],
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#10b981',
    routingStrategy: 'probability',
    connections: [
      { targetId: 'routing-standard-intake', probability: 0.7, itemProfileIds: ['standard'] },
      { targetId: 'routing-vip-intake', probability: 0.3, itemProfileIds: ['vip'] },
    ],
    x: 80,
    y: 300,
  },
  {
    id: 'routing-standard-intake',
    type: 'process',
    name: 'Standard Intake Router',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 2,
    processingTime: 1,
    processingTimeUnit: 'min',
    variance: 0,
    minProcessingTime: 0.75,
    maxProcessingTime: 1.5,
    rangeTimeUnit: 'min',
    failureProbability: 0,
    cancellationProbability: 0.00005,
    color: '#0ea5e9',
    routingStrategy: 'time-aware',
    routingTimeSensitivity: 4,
    routingCalendarAware: true,
    connections: [
      { targetId: 'routing-general-a', probability: 0.5, maxPriority: 4 },
      { targetId: 'routing-general-b', probability: 0.5, maxPriority: 4 },
    ],
    x: 430,
    y: 170,
  },
  {
    id: 'routing-vip-intake',
    type: 'process',
    name: 'VIP Intake Gate',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 1,
    processingTime: 0.75,
    processingTimeUnit: 'min',
    variance: 0,
    minProcessingTime: 0.5,
    maxProcessingTime: 1,
    rangeTimeUnit: 'min',
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#d946ef',
    routingStrategy: 'load-aware',
    routingLoadSensitivity: 3,
    connections: [
      { targetId: 'routing-vip-lane', probability: 0.85, minPriority: 5 },
      { targetId: 'routing-general-b', probability: 0.15, minPriority: 5 },
    ],
    x: 430,
    y: 520,
  },
  {
    id: 'routing-general-a',
    type: 'process',
    name: 'General Team A (Small)',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    calendarMode: 'custom',
    businessCalendar: {
      enabled: true,
      daysOfWeek: [1, 2, 3, 4, 5],
      workingHours: [{ start: 13, end: 17 }],
      nonWorkingArrivalPolicy: 'queue',
    },
    resourceExecutionMode: 'single',
    capacity: 1,
    processingTime: 8,
    processingTimeUnit: 'min',
    variance: 0.1,
    minProcessingTime: 6,
    maxProcessingTime: 10,
    rangeTimeUnit: 'min',
    failureProbability: 0.01,
    cancellationProbability: 0,
    color: '#f59e0b',
    connections: [{ targetId: 'routing-quality-check', probability: 1 }],
    x: 840,
    y: 90,
  },
  {
    id: 'routing-general-b',
    type: 'process',
    name: 'General Team B (Elastic)',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 3,
    processingTime: 7,
    processingTimeUnit: 'min',
    variance: 0.1,
    minProcessingTime: 5,
    maxProcessingTime: 9,
    rangeTimeUnit: 'min',
    failureProbability: 0.01,
    cancellationProbability: 0,
    color: '#22c55e',
    connections: [{ targetId: 'routing-quality-check', probability: 1 }],
    x: 840,
    y: 330,
  },
  {
    id: 'routing-vip-lane',
    type: 'process',
    name: 'VIP Fast Lane',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 2,
    processingTime: 4,
    processingTimeUnit: 'min',
    variance: 0.05,
    minProcessingTime: 3,
    maxProcessingTime: 5,
    rangeTimeUnit: 'min',
    failureProbability: 0.005,
    cancellationProbability: 0,
    color: '#ec4899',
    connections: [{ targetId: 'routing-quality-check', probability: 1, minPriority: 5 }],
    x: 840,
    y: 570,
  },
  {
    id: 'routing-quality-check',
    type: 'process',
    name: 'Unified Quality Check',
    randomnessMode: 'fixed',
    simulationMode: 'resource',
    resourceExecutionMode: 'single',
    capacity: 2,
    processingTime: 2,
    processingTimeUnit: 'min',
    variance: 0.05,
    minProcessingTime: 1,
    maxProcessingTime: 3,
    rangeTimeUnit: 'min',
    failureProbability: 0.01,
    cancellationProbability: 0,
    color: '#8b5cf6',
    connections: [{ targetId: 'routing-end', probability: 1 }],
    x: 1260,
    y: 330,
  },
  {
    id: 'routing-end',
    type: 'end',
    name: 'Resolved / Delivered',
    randomnessMode: 'fixed',
    capacity: 0,
    processingTime: 0,
    variance: 0,
    endTimeUnit: 'min',
    failureProbability: 0,
    cancellationProbability: 0,
    color: '#ef4444',
    connections: [],
    x: 1640,
    y: 330,
  },
];

export const ROUTING_DEMO_CONFIG: SimulationConfig = {
  steps: ROUTING_DEMO_STEPS,
  isRunning: false,
  speedMultiplier: 1,
  timeCompression: 60 * 60,
  simulationMode: 'realistic',
  calendarStartIso: '2026-01-05T09:00:00',
  businessCalendar: {
    enabled: true,
    daysOfWeek: [1, 2, 3, 4, 5],
    workingHours: [{ start: 9, end: 17 }],
    nonWorkingArrivalPolicy: 'queue',
  },
  waitTimeCalculationMode: 'both',
};

export const DEFAULT_CONFIG: SimulationConfig = {
  steps: DEFAULT_STEPS,
  isRunning: false,
  speedMultiplier: 1,
  timeCompression: 1,
  simulationMode: 'realistic',
};
